site_name: WOLF
theme:
  language: en
  name: material
  features:
    - navigation.tabs
  logo: assets/logo.jpg
  palette:
    scheme: slate
    primary: light green
    accent: indigo
    
copyright: Copyright &copy; 2022 Calvin Kimani

extra:
  generator: false
